### ISSUE TITLE
Add Java Programs

### ISSUE THREAD

**Issue by avichalsri** [avichalsri/Resources#152]

**Comment by haseeb-xd** [comment]
I want to work on Java programs

**Comment by avichalsri** [comment]
Hi @haseeb-xd, the issue is created for hacktoberfest explicitly, you can work on it as part of Hacktoberfest to be held next month in October. Will assign next month only.

Thanks for your interest. Stay tuned!

**Comment by snehalsenapati23** [comment]
Hey @avichalsri i want to work on this.
can i?

**Comment by MayaSatishRao** [comment]
Hi @avichalsri I want to work on this issue? Can you assign this issue to me?

**Comment by avichalsri** [comment]
Hi @snehalsenapati23 @MayaSatishRao ,these are generic issues to denote what type of contributions I am looking for. Kindly create your individual issues with the program/code you are going to add and I will assign that to you.
Do note creating an issue is not mandatory, you can directly create a PR with the program code and once verified, that would be accepted for Hacktoberfest.
Thanks for your interest and looking forward to your contributions!

**Comment by avichalsri** [comment]
Repo excluded from Hacktoberfest 2022.
