### ISSUE TITLE
Add Python Programs

### ISSUE THREAD

**Issue by avichalsri** [avichalsri/Resources#153]

**Comment by ShishuSidharth** [comment]
can you please guide what exactly we need to do?

**Comment by avichalsri** [comment]
Hi @ShishuSidharth , the ask to add some common and important python codes to the repo to enhance the content of the repo and help other users with the codes.

**Comment by cyrilckurian** [comment]
hello ,i would like to work on this issue, can you assign this to me @avichalsri

**Comment by avichalsri** [comment]
Hi @cyrilckurian, this is a general issue describing what contributions the repo requires. Whatever program or code you are adding, you can raise an issue for that, and I will assign that you only in October month since this repo is mainly for Hacktoberfest 2022.

You can add an issue now or in October and I will assign that you only in October and then you can work on it.

**Comment by cyrilckurian** [comment]
ok👍

**Comment by cyrilckurian** [comment]
I'm participating in Hacktoberfest 2022 and I would like to add python programs. Can I make PR after Oct 1st?

**Comment by avichalsri** [comment]
Yes ofcourse, do contribute.
Appreciate your contribution!

**Comment by avichalsri** [comment]
Repo excluded from Hacktoberfest 2022.
