### ISSUE TITLE
Add C++ Programs

### ISSUE THREAD

**Issue by avichalsri** [avichalsri/Resources#154]

**Comment by saimaheshtaduri** [comment]
I can add some important algorithmic programs in C++. assign the issue to me. @avichalsri

**Comment by vikash485** [comment]
Hello @avichalsri, can you give a brief description of what this issue is meant for? I would like to contribute for Hacktoberfest.

**Comment by avichalsri** [comment]
Hi @vikash485, thanks for showing interest. You can checkout my above comment.
In short, if you have a good well written program for some algorithmic problem, raise a PR with its code in October and it will be merged to the repo, after reviewing.

**Comment by avichalsri** [comment]
Repo excluded from Hacktoberfest 2022.
