### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by avichalsri** [avichalsri/Resources#157]
Add CONTRIBUTING.md with all the basic details.

**Comment by Pranjalmishra30** [comment]
Hi I would like to work on this issue

**Comment by avichalsri** [comment]
Hi @Pranjalmishra30, thanks for your interest. Do you want to work on it now or in Hacktoberfest? 

If you do it now, it won't be counted in Hacktoberfest.

**Comment by ujwxl23** [comment]
Hi, how can i work on this for the Hacktober-fest??
This is my first time participating in it.

**Comment by avichalsri** [comment]
Create the file in the root the root folder and raise a PR.

**Comment by avichalsri** [comment]
@Pranjalmishra30 @ujwxl23 anybody available to work on this, I want this to be completed soon.

**Comment by Pranjalmishra30** [comment]
Sure will raise a PR soon

**Comment by avichalsri** [comment]
Thanks @Pranjalmishra30 , assigned to you.

**Comment by avichalsri** [comment]
Resolved with #222
