### ISSUE TITLE
Verify a number is palindromic or not in C++

### ISSUE THREAD

**Issue by rithwik003** [avichalsri/Resources#158]
@avichalsri i want to work on this issue for Hacktoberfest 2022 , so can you please assign this issue to me.

**Comment by avichalsri** [comment]
Hi @rithwik003 everything in October please.

**Comment by rithwik003** [comment]
Ok bro.

**Comment by rithwik003** [comment]
@avichalsri can you assign this now.

**Comment by avichalsri** [comment]
@rithwik003 assigned.

**Comment by avichalsri** [comment]
Resolved with #169
