### ISSUE TITLE
Move programs in root folder to respective folders

### ISSUE THREAD

**Issue by avichalsri** [avichalsri/Resources#177]
There are 2 programs of Python and 2 programs of CPP in the root folder, move them into respective python and cpp folders.

**Comment by Nainish-Rai** [comment]
Hey, I would like to help, Kindly assign me.

**Comment by avichalsri** [comment]
Thanks @Nainish-Rai. Assigned.
It would be great if you can work on this today.
Assigned.

**Comment by Nainish-Rai** [comment]
@avichalsri I have made the required changes; And opened a pull request,Kindly check.

**Comment by avichalsri** [comment]
Closed with #180 
Thanks @Nainish-Rai
